### ISSUE TITLE
Issue with num_process while running trpo_mujoco script

### ISSUE THREAD

**Issue by surajpedasingu** [RITCHIEHuang/DeepRL_Algorithms#6] opened 2021-01-20 19:25 UTC
Terminal freezes without any error. There is some bug related to multiprocessing in the memory collector class.

**Comment by RITCHIEHuang** [comment] 2021-01-21 04:35
@surajpedasingu Thanks for pointing out the bug, the memory collector was designed to compatible for multiprocessing to accelerate the sampling step, you can set `num_process=1` just to verify the algorithm itself, I will try to fix the bug as soon as possible.

**Comment by RITCHIEHuang** [comment] 2021-01-21 06:35
@surajpedasingu The bug caused by multiprocessing package is incompatible with torch, now it's fixed now, and you can check it.

**Comment by surajpedasingu** [comment] 2021-01-23 11:00
@RITCHIEHuang Yes it was working with `num_process=1`. I dont understand how are you trying to acclerate sampling when the underlying policy and env are single objects and the same objects are being passed to multiple processes. In this case, sampling wont be accelerated as processes will be executed in sequential order because underlying objects will be locked when one process is using them. Correct me if I'm wrong?

**Comment by RITCHIEHuang** [comment] 2021-01-23 19:56
@surajpedasingu Yeah, here the collector use multi processes to collect samples without updating the policy parameters, the policy & env itselves is not changed, we still can use less time to sample same samples.

**Closed** 2021-02-01 04:33 UTC
